[package]
authors = ["Walfie <walfington@gmail.com>"]
name = "phash"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
image = "0.14"
tokio-core = "0.1"

