use self::Language::*;

macro_rules! boss {
    ($name:expr, $level:expr, $language:ident, $url:expr) => {
        Boss {
            name: $name,
            level: $level,
            language: $language,
            url: $url
        }
    }
}

#[derive(Debug, PartialEq)]
pub enum Language {
    En,
    Ja,
}

#[derive(Debug, PartialEq)]
pub struct Boss {
    pub name: &'static str,
    pub level: u8,
    pub language: Language,
    pub url: &'static str,
}

#[cfg_attr(rustfmt, rustfmt_skip)]
pub const BOSSES: &[Boss] = &[
    //
    // Japanese bosses
    //

    // Guild Wars
    boss!("Lv30 アーフラー", 30, Ja, "https://pbs.twimg.com/media/CeSO4quUYAAy8U1.jpg"),
    boss!("Lv40 アーフラー", 40, Ja, "https://pbs.twimg.com/media/CeSO6aAWAAAAOGe.jpg"),
    boss!("Lv40 ゲイザー", 40, Ja, "https://pbs.twimg.com/media/Cn7opV5VUAAfgDz.jpg"),
    boss!("Lv40 ヨグ＝ソトース", 40, Ja, "https://pbs.twimg.com/media/Cqlrx16VUAAU1-Z.jpg"),
    boss!("Lv50 ベオウルフ", 50, Ja, "https://pbs.twimg.com/media/CeSO8gHWAAEnMGl.jpg"),
    boss!("Lv60 グガランナ", 60, Ja, "https://pbs.twimg.com/media/Cn7o2sYVYAEP45o.jpg"),
    boss!("Lv60 ベオウルフ", 60, Ja, "https://pbs.twimg.com/media/CeSO-QrWwAECCG1.jpg"),
    boss!("Lv60 マヒシャ", 60, Ja, "https://pbs.twimg.com/media/Cqlr4E5VMAAOGqb.jpg"),
    boss!("Lv75 エメラルドホーン", 75, Ja, "https://pbs.twimg.com/media/Cn7o767UkAEX8-H.jpg"),
    boss!("Lv75 スーペルヒガンテ", 75, Ja, "https://pbs.twimg.com/media/Cqlr_RRVYAEabiO.jpg"),

    // Standard
    boss!("Lv20 グリフォン", 20, Ja, "https://pbs.twimg.com/media/CT6cKZPUsAEb4aA.jpg"),
    boss!("Lv30 コロッサス", 30, Ja, "https://pbs.twimg.com/media/CT6cUf8VEAEBaEb.jpg"),
    boss!("Lv50 アドウェルサ", 50, Ja, "https://pbs.twimg.com/media/CT6cgc5UYAIhJoB.jpg"),
    boss!("Lv50 コロッサス", 50, Ja, "https://pbs.twimg.com/media/CT6cUf8VEAEBaEb.jpg"),
    boss!("Lv50 セレスト", 50, Ja, "https://pbs.twimg.com/media/CT6cmzjUcAIvSo_.jpg"),
    boss!("Lv50 ティアマト", 50, Ja, "https://pbs.twimg.com/media/CT6cLx4VAAAzePV.jpg"),
    boss!("Lv50 ティアマト・マグナ", 50, Ja, "https://pbs.twimg.com/media/CT6buTPUwAIM9VJ.jpg"),
    boss!("Lv50 ユグドラシル", 50, Ja, "https://pbs.twimg.com/media/CT6cbScU8AAgXRw.jpg"),
    boss!("Lv50 リヴァイアサン", 50, Ja, "https://pbs.twimg.com/media/CT6cXcgUEAEc0Zl.jpg"),
    boss!("Lv60 ユグドラシル・マグナ", 60, Ja, "https://pbs.twimg.com/media/CT6cDD3UkAEnP8Y.jpg"),
    boss!("Lv60 リヴァイアサン・マグナ", 60, Ja, "https://pbs.twimg.com/media/CT6cBK3U8AA4xdW.jpg"),
    boss!("Lv70 コロッサス・マグナ", 70, Ja, "https://pbs.twimg.com/media/CT6bwJTUYAA6mcV.jpg"),
    boss!("Lv75 シュヴァリエ・マグナ", 75, Ja, "https://pbs.twimg.com/media/CT6cEwEUcAAlwFM.jpg"),
    boss!("Lv75 セレスト・マグナ", 75, Ja, "https://pbs.twimg.com/media/CT6cGF4UYAAHBg5.jpg"),
    boss!("Lv100 Dエンジェル・オリヴィエ", 100, Ja, "https://pbs.twimg.com/media/CT6csqNVAAA_GFU.jpg"),
    boss!("Lv100 アテナ", 100, Ja, "https://pbs.twimg.com/media/Cg7oAJsUkAApRif.jpg"),
    boss!("Lv100 アポロン", 100, Ja, "https://pbs.twimg.com/media/CT6chwtUsAA0WFw.jpg"),
    boss!("Lv100 ウリエル", 100, Ja, "https://pbs.twimg.com/media/C66623wU8AACyL2.jpg"),
    boss!("Lv100 オーディン", 100, Ja, "https://pbs.twimg.com/media/CqwDU_jUkAQjgKq.jpg"),
    boss!("Lv100 ガブリエル", 100, Ja, "https://pbs.twimg.com/media/C6666EXU4AE8ENT.jpg"),
    boss!("Lv100 ガルーダ", 100, Ja, "https://pbs.twimg.com/media/CkVbhuqVEAA7e6K.jpg"),
    boss!("Lv100 グラニ", 100, Ja, "https://pbs.twimg.com/media/CqwDXDkUMAAjCE5.jpg"),
    boss!("Lv100 コロッサス・マグナ", 100, Ja, "https://pbs.twimg.com/media/CVL2CmeUwAAElDW.jpg"),
    boss!("Lv100 シュヴァリエ・マグナ", 100, Ja, "https://pbs.twimg.com/media/CbTeQ1fVIAAEoqi.jpg"),
    boss!("Lv100 ジ・オーダー・グランデ", 100, Ja, "https://pbs.twimg.com/media/CdL4YeiUEAI0JKW.jpg"),
    boss!("Lv100 セレスト・マグナ", 100, Ja, "https://pbs.twimg.com/media/CbTeWuMUUAIzFZl.jpg"),
    boss!("Lv100 ティアマト・マグナ＝エア", 100, Ja, "https://pbs.twimg.com/media/CT6cNUBUAAETdz6.jpg"),
    boss!("Lv100 ドゥンケルハイト", 100, Ja, "https://pbs.twimg.com/media/DC-V74TUQAAHP-j.jpg"),
    boss!("Lv100 ナタク", 100, Ja, "https://pbs.twimg.com/media/CT6cOzzUwAESsq_.jpg"),
    boss!("Lv100 バアル", 100, Ja, "https://pbs.twimg.com/media/CjLxgrbUgAAFbwi.jpg"),
    boss!("Lv100 フラム＝グラス", 100, Ja, "https://pbs.twimg.com/media/CT_qpfCUsAA9vfF.jpg"),
    boss!("Lv100 プロトバハムート", 100, Ja, "https://pbs.twimg.com/media/CT6cIKmUYAAPVmD.jpg"),
    boss!("Lv100 マキュラ・マリウス", 100, Ja, "https://pbs.twimg.com/media/CT6cYp-UsAAy_f0.jpg"),
    boss!("Lv100 ミカエル", 100, Ja, "https://pbs.twimg.com/media/C6668rmVsAAjpu1.jpg"),
    boss!("Lv100 メドゥーサ", 100, Ja, "https://pbs.twimg.com/media/CT6ccesVEAAy_Kx.jpg"),
    boss!("Lv100 ユグドラシル・マグナ", 100, Ja, "https://pbs.twimg.com/media/CYBkhTmUsAAPjgu.jpg"),
    boss!("Lv100 ラファエル", 100, Ja, "https://pbs.twimg.com/media/C666_h3V0AAQvt4.jpg"),
    boss!("Lv100 リッチ", 100, Ja, "https://pbs.twimg.com/media/CqwDZKwVMAAxt0Y.jpg"),
    boss!("Lv100 リヴァイアサン・マグナ", 100, Ja, "https://pbs.twimg.com/media/CYBkbZSUAAA2BW-.jpg"),
    boss!("Lv100 黄龍", 100, Ja, "https://pbs.twimg.com/media/ClrgFhVVYAECRRD.jpg"),
    boss!("Lv100 黒麒麟", 100, Ja, "https://pbs.twimg.com/media/ClrgH4wUYAAax1o.jpg"),
    boss!("Lv110 ローズクイーン", 110, Ja, "https://pbs.twimg.com/media/CUnrstgUYAA4hOz.jpg"),
    boss!("Lv120 Dエンジェル・オリヴィエ", 120, Ja, "https://pbs.twimg.com/media/CbTeSqbUcAARoNV.jpg"),
    boss!("Lv120 アヌビス", 120, Ja, "https://pbs.twimg.com/media/CzcJCMtVEAEbPjY.jpg"),
    boss!("Lv120 アポロン", 120, Ja, "https://pbs.twimg.com/media/CbTeO4fUkAEmmIN.jpg"),
    boss!("Lv120 カー・オン", 120, Ja, "https://pbs.twimg.com/media/Cs1w3NXVMAAAiRy.jpg"),
    boss!("Lv120 ギルガメッシュ", 120, Ja, "https://pbs.twimg.com/media/CqG0X1tUkAA5B8_.jpg"),
    boss!("Lv120 ナタク", 120, Ja, "https://pbs.twimg.com/media/CT6cQD-UcAE3nt2.jpg"),
    boss!("Lv120 バイヴカハ", 120, Ja, "https://pbs.twimg.com/media/CucwemxVUAA7pWF.jpg"),
    boss!("Lv120 フラム＝グラス", 120, Ja, "https://pbs.twimg.com/media/CVL2EBHUwAA8nUj.jpg"),
    boss!("Lv120 プロメテウス", 120, Ja, "https://pbs.twimg.com/media/CqG0anMUIAU6z7f.jpg"),
    boss!("Lv120 ヘクトル", 120, Ja, "https://pbs.twimg.com/media/CyEeWDkUQAQ5DzW.jpg"),
    boss!("Lv120 マキュラ・マリウス", 120, Ja, "https://pbs.twimg.com/media/CYBkd_1UEAATH9J.jpg"),
    boss!("Lv150 プロトバハムート", 150, Ja, "https://pbs.twimg.com/media/CdL4WyxUYAIXPb8.jpg"),

    //
    // English bosses
    //

    // Guild Wars
    boss!("Lvl 30 Ahura", 30, En, "https://pbs.twimg.com/media/Cs1w7-QUIAApnHh.jpg"),
    boss!("Lvl 40 Ahura", 40, En, "https://pbs.twimg.com/media/Cs1w9nhVIAABgqg.jpg"),
    boss!("Lvl 40 Ogler", 40, En, "https://pbs.twimg.com/media/Cn7oqbPUkAEimW2.jpg"),
    boss!("Lvl 40 Yog-Sothoth", 40, En, "https://pbs.twimg.com/media/Cqlr0pRVUAQxZ5g.jpg"),
    boss!("Lvl 50 Grendel", 50, En, "https://pbs.twimg.com/media/Cs1w-68UEAEjhEV.jpg"),
    boss!("Lvl 60 Grendel", 60, En, "https://pbs.twimg.com/media/Cs1xAKcVIAEXC9a.jpg"),
    boss!("Lvl 60 Gugalanna", 60, En, "https://pbs.twimg.com/media/Cn7o6ppVUAArahp.jpg"),
    boss!("Lvl 60 Mahisha", 60, En, "https://pbs.twimg.com/media/Cqlr51CUAAA9lp3.jpg"),
    boss!("Lvl 75 Supergigante", 75, En, "https://pbs.twimg.com/media/CqlsAzGUkAAAcRT.jpg"),
    boss!("Lvl 75 Viridian Horn", 75, En, "https://pbs.twimg.com/media/Cn7o85cUEAAnlh0.jpg"),

    // Standard
    boss!("Lvl 20 Griffin", 20, En, "https://pbs.twimg.com/media/CfqWxZGUIAASb34.jpg"),
    boss!("Lvl 30 Ancient Dragon", 30, En, "https://pbs.twimg.com/media/CfqXBeqUAAEdgUN.jpg"),
    boss!("Lvl 30 Colossus", 30, En, "https://pbs.twimg.com/media/CfqW62PUAAA6QTY.jpg"),
    boss!("Lvl 30 Evil Eye", 30, En, "https://pbs.twimg.com/media/CfqXKHgUAAE7g9c.jpg"),
    boss!("Lvl 50 Adversa", 50, En, "https://pbs.twimg.com/media/CfqXHXPUUAAh0PQ.jpg"),
    boss!("Lvl 50 Celeste", 50, En, "https://pbs.twimg.com/media/CfqXLhHUEAAF92L.jpg"),
    boss!("Lvl 50 Colossus", 50, En, "https://pbs.twimg.com/media/CfqW62PUAAA6QTY.jpg"),
    boss!("Lvl 50 Leviathan", 50, En, "https://pbs.twimg.com/media/CfqW-MVUIAEJrDP.jpg"),
    boss!("Lvl 50 Tiamat Omega", 50, En, "https://pbs.twimg.com/media/CfqXQA3UMAEMV7O.jpg"),
    boss!("Lvl 50 Tiamat", 50, En, "https://pbs.twimg.com/media/CfqWy2tUUAAr9yu.jpg"),
    boss!("Lvl 50 Yggdrasil", 50, En, "https://pbs.twimg.com/media/CfqXDAQVIAAixiA.jpg"),
    boss!("Lvl 60 Leviathan Omega", 60, En, "https://pbs.twimg.com/media/CfqXTAQUAAAu3ox.jpg"),
    boss!("Lvl 60 Yggdrasil Omega", 60, En, "https://pbs.twimg.com/media/CfuZgxLUkAArdGe.jpg"),
    boss!("Lvl 70 Colossus Omega", 70, En, "https://pbs.twimg.com/media/CfqXRjsUAAAwXTP.jpg"),
    boss!("Lvl 75 Celeste Omega", 75, En, "https://pbs.twimg.com/media/CfqXXVDUUAA0hAS.jpg"),
    boss!("Lvl 75 Luminiera Omega", 75, En, "https://pbs.twimg.com/media/CfqXWAhUsAAprzd.jpg"),
    boss!("Lvl 100 Apollo", 100, En, "https://pbs.twimg.com/media/CfqXI0lVAAAQgcj.jpg"),
    boss!("Lvl 100 Athena", 100, En, "https://pbs.twimg.com/media/Cg7oBQ_UYAEAIK7.jpg"),
    boss!("Lvl 100 Baal", 100, En, "https://pbs.twimg.com/media/CjLxhwmUoAEglVC.jpg"),
    boss!("Lvl 100 Celeste Omega", 100, En, "https://pbs.twimg.com/media/CfqZzDsUUAA5DEX.jpg"),
    boss!("Lvl 100 Colossus Omega", 100, En, "https://pbs.twimg.com/media/CfqZOt6VIAAniVV.jpg"),
    boss!("Lvl 100 Dark Angel Olivia", 100, En, "https://pbs.twimg.com/media/CfqXOjEUMAAXuK2.jpg"),
    boss!("Lvl 100 Dunkelheit", 100, En, "https://pbs.twimg.com/media/DC-WAU1VwAAElDk.jpg"),
    boss!("Lvl 100 Gabriel", 100, En, "https://pbs.twimg.com/media/C6667Y-V4AAge7r.jpg"),
    boss!("Lvl 100 Garuda", 100, En, "https://pbs.twimg.com/media/CkVbjdpUYAAmnvb.jpg"),
    boss!("Lvl 100 Grand Order", 100, En, "https://pbs.twimg.com/media/CfqaAYfUUAQqgpv.jpg"),
    boss!("Lvl 100 Grani", 100, En, "https://pbs.twimg.com/media/CqwDYIbVMAE0VUR.jpg"),
    boss!("Lvl 100 Huanglong", 100, En, "https://pbs.twimg.com/media/ClrgGy_VYAAz-yc.jpg"),
    boss!("Lvl 100 Leviathan Omega", 100, En, "https://pbs.twimg.com/media/CfqZfExVIAA4YgF.jpg"),
    boss!("Lvl 100 Lich", 100, En, "https://pbs.twimg.com/media/CqwDaPAVYAQAYzq.jpg"),
    boss!("Lvl 100 Luminiera Omega", 100, En, "https://pbs.twimg.com/media/CfqZvtlVIAAgBeF.jpg"),
    boss!("Lvl 100 Macula Marius", 100, En, "https://pbs.twimg.com/media/CfqXAC1UIAAeGl-.jpg"),
    boss!("Lvl 100 Medusa", 100, En, "https://pbs.twimg.com/media/CfqXEh_UsAEb9dw.jpg"),
    boss!("Lvl 100 Michael", 100, En, "https://pbs.twimg.com/media/C666-DPVAAAS94m.jpg"),
    boss!("Lvl 100 Nezha", 100, En, "https://pbs.twimg.com/media/CfqW0bzUMAAOJsU.jpg"),
    boss!("Lvl 100 Odin", 100, En, "https://pbs.twimg.com/media/CqwDWGjUIAEeJ4s.jpg"),
    boss!("Lvl 100 Proto Bahamut", 100, En, "https://pbs.twimg.com/media/CfqXYlBUAAQ1mtV.jpg"),
    boss!("Lvl 100 Qilin", 100, En, "https://pbs.twimg.com/media/ClrgI8vUoAEhtoU.jpg"),
    boss!("Lvl 100 Raphael", 100, En, "https://pbs.twimg.com/media/C667BN2U4AEm6Qq.jpg"),
    boss!("Lvl 100 Tiamat Omega Ayr", 100, En, "https://pbs.twimg.com/media/CfqW2SWUEAAMr7S.jpg"),
    boss!("Lvl 100 Twin Elements", 100, En, "https://pbs.twimg.com/media/CfqXaAvUIAEUC8B.jpg"),
    boss!("Lvl 100 Uriel", 100, En, "https://pbs.twimg.com/media/C6664nkVAAASGPu.jpg"),
    boss!("Lvl 100 Yggdrasil Omega", 100, En, "https://pbs.twimg.com/media/Cfv1i6wUsAAZajc.jpg"),
    boss!("Lvl 110 Rose Queen", 110, En, "https://pbs.twimg.com/media/CfqZNDiUEAEkvHp.jpg"),
    boss!("Lvl 120 Anubis", 120, En, "https://pbs.twimg.com/media/CzcJDQgUoAAgX-J.jpg"),
    boss!("Lvl 120 Apollo", 120, En, "https://pbs.twimg.com/media/CfqZxihUEAEzcG-.jpg"),
    boss!("Lvl 120 Ca Ong", 120, En, "https://pbs.twimg.com/media/Cs1w4gfUsAAwzdf.jpg"),
    boss!("Lvl 120 Dark Angel Olivia", 120, En, "https://pbs.twimg.com/media/CfqZ3BwVIAEtIgy.jpg"),
    boss!("Lvl 120 Gilgamesh", 120, En, "https://pbs.twimg.com/media/CqG0ZPiUsAA4yW8.jpg"),
    boss!("Lvl 120 Hector", 120, En, "https://pbs.twimg.com/media/CyEeXQaUkAAVW1R.jpg"),
    boss!("Lvl 120 Macula Marius", 120, En, "https://pbs.twimg.com/media/CfqZhE0UsAA_JqS.jpg"),
    boss!("Lvl 120 Morrigna", 120, En, "https://pbs.twimg.com/media/Cucwk8yUEAAZzbO.jpg"),
    boss!("Lvl 120 Nezha", 120, En, "https://pbs.twimg.com/media/CfqW4BYUEAAeYSR.jpg"),
    boss!("Lvl 120 Prometheus", 120, En, "https://pbs.twimg.com/media/CqG0bnLUkAAZpVs.jpg"),
    boss!("Lvl 120 Twin Elements", 120, En, "https://pbs.twimg.com/media/CfqZQ_pUEAAQFI4.jpg"),
    boss!("Lvl 150 Proto Bahamut", 150, En, "https://pbs.twimg.com/media/CfqZ-YtVAAAt5qd.jpg"),
];

#[cfg_attr(rustfmt, rustfmt_skip)]
pub const EXPECTED_PAIRS: &[(&'static str, &'static str)] = &[
    // Guild Wars
    ("Lv30 アーフラー", "Lvl 30 Ahura"),
    ("Lv40 アーフラー", "Lvl 40 Ahura"),
    ("Lv40 ゲイザー", "Lvl 40 Ogler"),
    ("Lv40 ヨグ＝ソトース", "Lvl 40 Yog-Sothoth"),
    ("Lv50 ベオウルフ", "Lvl 50 Grendel"),
    ("Lv60 グガランナ", "Lvl 60 Gugalanna"),
    ("Lv60 ベオウルフ", "Lvl 60 Grendel"),
    ("Lv60 マヒシャ", "Lvl 60 Mahisha"),
    ("Lv75 エメラルドホーン", "Lvl 75 Viridian Horn"),
    ("Lv75 スーペルヒガンテ", "Lvl 75 Supergigante"),

    // Standard
    ("Lv20 グリフォン", "Lvl 20 Griffin"),
    ("Lv30 コロッサス", "Lvl 30 Colossus"),
    ("Lv50 アドウェルサ", "Lvl 50 Adversa"),
    ("Lv50 コロッサス", "Lvl 50 Colossus"),
    ("Lv50 セレスト", "Lvl 50 Celeste"),
    ("Lv50 ティアマト", "Lvl 50 Tiamat"),
    ("Lv50 ティアマト・マグナ", "Lvl 50 Tiamat Omega"),
    ("Lv50 ユグドラシル", "Lvl 50 Yggdrasil"),
    ("Lv50 リヴァイアサン", "Lvl 50 Leviathan"),
    ("Lv60 ユグドラシル・マグナ", "Lvl 60 Yggdrasil Omega"),
    ("Lv60 リヴァイアサン・マグナ", "Lvl 60 Leviathan Omega"),
    ("Lv70 コロッサス・マグナ", "Lvl 70 Colossus Omega"),
    ("Lv75 シュヴァリエ・マグナ", "Lvl 75 Luminiera Omega"),
    ("Lv75 セレスト・マグナ", "Lvl 75 Celeste Omega"),
    ("Lv100 Dエンジェル・オリヴィエ", "Lvl 100 Dark Angel Olivia"),
    ("Lv100 アテナ", "Lvl 100 Athena"),
    ("Lv100 アポロン", "Lvl 100 Apollo"),
    ("Lv100 ウリエル", "Lvl 100 Uriel"),
    ("Lv100 オーディン", "Lvl 100 Odin"),
    ("Lv100 ガブリエル", "Lvl 100 Gabriel"),
    ("Lv100 ガルーダ", "Lvl 100 Garuda"),
    ("Lv100 グラニ", "Lvl 100 Grani"),
    ("Lv100 コロッサス・マグナ", "Lvl 100 Colossus Omega"),
    ("Lv100 シュヴァリエ・マグナ", "Lvl 100 Luminiera Omega"),
    ("Lv100 ジ・オーダー・グランデ", "Lvl 100 Grand Order"),
    ("Lv100 セレスト・マグナ", "Lvl 100 Celeste Omega"),
    ("Lv100 ティアマト・マグナ＝エア", "Lvl 100 Tiamat Omega Ayr"),
    ("Lv100 ドゥンケルハイト", "Lvl 100 Dunkelheit"),
    ("Lv100 ナタク", "Lvl 100 Nezha"),
    ("Lv100 バアル", "Lvl 100 Baal"),
    ("Lv100 フラム＝グラス", "Lvl 100 Twin Elements"),
    ("Lv100 プロトバハムート", "Lvl 100 Proto Bahamut"),
    ("Lv100 マキュラ・マリウス", "Lvl 100 Macula Marius"),
    ("Lv100 ミカエル", "Lvl 100 Michael"),
    ("Lv100 メドゥーサ", "Lvl 100 Medusa"),
    ("Lv100 ユグドラシル・マグナ", "Lvl 100 Yggdrasil Omega"),
    ("Lv100 ラファエル", "Lvl 100 Raphael"),
    ("Lv100 リッチ", "Lvl 100 Lich"),
    ("Lv100 リヴァイアサン・マグナ", "Lvl 100 Leviathan Omega"),
    ("Lv100 黄龍", "Lvl 100 Huanglong"),
    ("Lv100 黒麒麟", "Lvl 100 Qilin"),
    ("Lv110 ローズクイーン", "Lvl 110 Rose Queen"),
    ("Lv120 Dエンジェル・オリヴィエ", "Lvl 120 Dark Angel Olivia"),
    ("Lv120 アヌビス", "Lvl 120 Anubis"),
    ("Lv120 アポロン", "Lvl 120 Apollo"),
    ("Lv120 カー・オン", "Lvl 120 Ca Ong"),
    ("Lv120 ギルガメッシュ", "Lvl 120 Gilgamesh"),
    ("Lv120 ナタク", "Lvl 120 Nezha"),
    ("Lv120 バイヴカハ", "Lvl 120 Morrigna"),
    ("Lv120 フラム＝グラス", "Lvl 120 Twin Elements"),
    ("Lv120 プロメテウス", "Lvl 120 Prometheus"),
    ("Lv120 ヘクトル", "Lvl 120 Hector"),
    ("Lv120 マキュラ・マリウス", "Lvl 120 Macula Marius"),
    ("Lv150 プロトバハムート", "Lvl 150 Proto Bahamut"),
];
